<h3 style="box-sizing: border-box; margin: 20px 0px 10px; font-size: 24px; line-height: 1.1; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; color: rgb(51, 51, 51); background-color: rgb(255, 255, 255); text-align: center;"><span style="box-sizing: border-box; color: rgb(255, 0, 0);"><strong style="box-sizing: border-box;">BẢNG GIÁ TAXI&nbsp;<span style="box-sizing: border-box;">TỪ HÀ NỘI LÊN SÂN BAY NỘI BÀI</span></strong></span></h3>

<table border="3" style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; background-color: rgb(255, 255, 255); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; height: 466px; border-color: rgb(44, 135, 8); margin-left: auto; margin-right: auto;width:100%">
    <tbody style="box-sizing: border-box;">
    <tr style="box-sizing: border-box; height: 24px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">STT</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">TUYẾN ĐƯỜNG&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">GIÁ XE 5 CHỖ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">GIÁ XE 7 CHỖ</span></td></tr>

    <tr style="box-sizing: border-box; height: 24px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">1</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 24px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN TÂY HỒ -&gt; SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">160.000đ - 180.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">220.000đ - 250.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 24px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">2</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 24px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN CẦU GIẤY -&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">170.000đ - 190.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">220.000đ - 250.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 24px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">3</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 24px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN HOÀN KIẾM -&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">160.000đ - 180.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">220.000đ - 250.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">4</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN BẮC TỪ LIÊM -&gt;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">180.000đ - 200.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">230.000đ - 250.000đ&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">5</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN BA ĐÌNH -&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">160.000đ - 180.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">220.000đ - 250.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">6</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN NAM TỪ LIÊM -&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">180.000đ - 220.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">230.000đ - 270.000đ&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">7&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN ĐỐNG ĐA -&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">180.000đ - 220.000đ&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">230.000đ - 260.000đ&nbsp;&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">8&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN THANH XUÂN -&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">190.000đ - 230.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">230.000đ - 270.000đ&nbsp;&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">9&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN LONG BIÊN-&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">180.000đ - 220.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">230.000đ - 270.000đ&nbsp;&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">10&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN HAI BÀ TRƯNG -&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">190.000đ - 220.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">230.000đ - 270.000đ&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">11&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN HOÀNG MAI -&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;220.000đ - 250.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">240.000đ - 290.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">12&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN THANH TRÌ&nbsp;-&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;220.000đ - 250.000đ&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;250.000đ - 290.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 51px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">13&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 368px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">QUẬN HÀ ĐÔNG&nbsp;-&gt;&nbsp;</span><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI</span></td><td style="box-sizing: border-box; padding: 0px; width: 202px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;210.000đ - 250.000đ&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 255px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;250.000đ - 290.000đ&nbsp;</span></td></tr>
    </tbody>
</table>
<h3 style="box-sizing: border-box; margin: 20px 0px 10px; font-size: 24px; line-height: 1.1; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; color: rgb(51, 51, 51); background-color: rgb(255, 255, 255); text-align: center;"><span style="box-sizing: border-box; color: rgb(255, 0, 0);"><strong style="box-sizing: border-box;">BẢNG GIÁ TAXI&nbsp;<span style="box-sizing: border-box;">TỪ SÂN BAY NỘI BÀI VỀ HÀ NỘI</span></strong></span></h3>

<table border="3" style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; background-color: rgb(255, 255, 255); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; height: 473px; border-color: rgb(44, 135, 8); margin-left: auto; margin-right: auto;width:100%">
    <tbody style="box-sizing: border-box;">
    <tr style="box-sizing: border-box; height: 24px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">STT</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">TUYẾN ĐƯỜNG&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">GIÁ XE 5 CHỖ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">GIÁ XE 7 CHỖ</span></td></tr>

    <tr style="box-sizing: border-box; height: 24.3125px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 24.3125px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">1</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 24.3125px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN TÂY HỒ</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 24.3125px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">230.000đ - 250.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 24.3125px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;280.000đ - 290.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 24px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">2</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 24px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN CẦU GIẤY</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">230.000đ - 250.000đ&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">280.000đ - 290.000đ&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 24px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">3</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 24px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN HOÀN KIẾM</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">230.000đ - 250.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 24px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">280.000đ - 290.000đ&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">4</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN BẮC TỪ LIÊM</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;230.000đ - 250.000đ&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">280.000đ - 290.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">5</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN BA ĐÌNH</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;230.000đ - 250.000đ&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">280.000đ - 290.000đ&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">6</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN NAM TỪ LIÊM</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">250.000đ - 280.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;290.000đ - 320.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">7&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN ĐỐNG ĐA</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">250.000đ - 280.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">290.000đ - 320.000đ&nbsp;</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">8&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN THANH XUÂN</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">250.000đ - 280.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">290.000đ - 320.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">9&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN LONG BIÊN</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">250.000đ - 280.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">290.000đ - 320.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">10&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN HAI BÀ TRƯNG</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">250.000đ - 280.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">290.000đ - 320.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">11&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN HOÀNG MAI</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp; 250.000đ - 300.000đ&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">&nbsp;290.000đ - 340.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">12&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN THANH TRÌ</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">250.000đ - 300.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">290.000đ - 340.000đ</span></td></tr>

    <tr style="box-sizing: border-box; height: 25px;"><td style="box-sizing: border-box; padding: 0px; width: 49px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;">13&nbsp;</span></td><td style="box-sizing: border-box; padding: 0px; width: 376px; height: 25px;"><span style="box-sizing: border-box; font-size: 12pt;">SÂN BAY NỘI BÀI -&gt; QUẬN HÀ ĐÔNG</span></td><td style="box-sizing: border-box; padding: 0px; width: 204px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">250.000đ - 300.000đ</span></td><td style="box-sizing: border-box; padding: 0px; width: 256px; height: 25px; text-align: center;"><span style="box-sizing: border-box; font-size: 12pt;"><span style="box-sizing: border-box; font-size: 12pt;"></span></span><span style="box-sizing: border-box; font-size: 12pt;">290.000đ - 340.000đ
          <br>

          <br>
         </span></td></tr>
    </tbody>
</table>
<br><br>